### ISSUE TITLE
TCPextend-post_dissector.lua not working on macOS 10.13.2 (Build 17C88)

### ISSUE THREAD

**Issue by 065673** [gaddman/wireshark-tcpextend#5]
On Mac OSX High Sierra copied TCPextend-post_dissector.lua 
to /Applications/Wireshark.app/Contents/PlugIns then launched Wireshark, loaded a trace file then began packet inspection. Unfortunately the LUA didn't show any tcp extended info on this OS. 

macOS 10.13.2 (Build 17C88)

**Comment by gaddman** [comment]
Unfortunately I don't have a Mac to test on. What Wireshark version, and do other LUA plugins work OK? Also is the location right? [Wireshark docs](https://www.wireshark.org/docs/wsug_html_chunked/ChPluginFolders.html) suggest either the global plugin folder `%APPDIR%/Contents/PlugIns/wireshark`, otherwise `INSTALLDIR/lib/wireshark/plugins`

**Comment by masonke** [comment]
Works for me on Mojave 10.14.4 (18E226) with Wireshark 3.01
Drop the file into ~/.local/lib/wireshark/plugins . You may have to create the directories.

It has this odd message about a <Wireshark Lua Fake Item> above the TCP Extended Info window, but seems to work well otherwise

<img width="438" alt="lua-message" src="https://user-images.githubusercontent.com/1863778/56589383-1b1dcd00-65b3-11e9-9dc6-8046b8ba0890.png">

**Comment by gaddman** [comment]
Thanks @masonke. Regarding the odd message, I hadn't seen that before, but it appeared after changing my preferences to show hidden protocol items - see [this Wireshark question](https://ask.wireshark.org/question/4466/is-there-any-way-to-disable-wireshark-lua-fake-item-from-being-displayed/).
